Repository emberjs/website, pull requests merged in 2018-10, with the labels that each got.

#3599 [embertimes] Update template
  source/blog/embertimes-template.md
Labels: content :memo:

#3600 [embertimes] Add Hacktoberfest writeup 🎃
  source/blog/2018-10-05-the-ember-times-issue-67.md
Labels: content :memo:

#3604 Added section on CodeSandbox Ember
  source/blog/2018-10-05-the-ember-times-issue-67.md
Labels: content :memo:

#3607 [embertimes] Add update to Hacktoberfest writeup
  source/blog/2018-10-05-the-ember-times-issue-67.md
Labels: content :memo:

#3608 Update template
  source/blog/embertimes-template.md
Labels: content :memo:

#3590 Ember Times Issue 67
  source/blog/2018-09-28-the-ember-times-issue-66.md
  source/blog/2018-10-05-the-ember-times-issue-67.md
Labels: content :memo:

#3611 Adding Stockholm Tomster
  data/tomsters.yml
  source/images/tomsters/stockholm.png
Labels: content :memo:, hacktoberfest

#3624 #68 - Module Unification call for help / contributions
  source/blog/2018-10-12-the-ember-times-issue-68.md
Labels: content :memo:

#3629 [#embertimes] Add writeup on ember-flatpickr
  source/blog/2018-10-12-the-ember-times-issue-68.md
Labels: content :memo:

#3631 update wording
  source/blog/2018-10-12-the-ember-times-issue-68.md
Labels: content :memo:

#3632 Add intro, Ryan, copy edits, etc
  source/blog/2018-10-12-the-ember-times-issue-68.md
Labels: content :memo:

#3641 For Ember Times No. 69: JQuery + DS.Errors RFC + Contributors
  source/blog/2018-10-19-the-ember-times-issue-69.md
Labels: content :memo:

#3642 Added section on docs testing
  source/blog/2018-10-19-the-ember-times-issue-69.md
Labels: content :memo:

#3643 For EmberTimes No. 69: Add Section about Relationship Loading RFC
  source/blog/2018-10-19-the-ember-times-issue-69.md
Labels: content :memo:

#3644 Short writeup on EmberConf brainstorm
  source/blog/2018-10-19-the-ember-times-issue-69.md
Labels: content :memo:

#3636 Ember Times Issue 69
  source/blog/2018-10-12-the-ember-times-issue-68.md
  source/blog/2018-10-19-the-ember-times-issue-69.md
Labels: content :memo:

#3657 Add GraphQL writeup and copy edits
  source/blog/2018-10-26-the-ember-times-issue-70.md
Labels: content :memo:

#3638 Add Web App Manifest (fixes #2965)
  source/layout.erb
  source/manifest.json
Labels: needs submitter response

#3650 Ember Times Issue 70
  source/blog/2018-10-19-the-ember-times-issue-69.md
  source/blog/2018-10-26-the-ember-times-issue-70.md
Labels: content :memo:
